main: yy.gourlitburo.yeyaafk.Main
name: YeyaAFK
version: 0.0.1
api-version: 1.14
author: Zack Guard
description: An AFK plugin.
commands:
  yeyaafk:
    aliases: [afk]
    description: Use YeyaAFK.
    usage: "Usage: /afk [reload]"
permissions:
  yeyaafk.manage:
    default: op
